- src/_shared/js/messages.js
First and foremost, we need a way for our ads to use the guardian's webfonts. This is done via the `getWebfonts` service, that queries the page for webfonts and expects CSS `@font-face` declarations in return.
> Add the getWebfonts API

- preview/server.js
- preview/src/js/lib/messenger.js
- src/_shared/js/messages.js
Some components may require that we simultaneously run frontend, which also runs on port 9000. Changing this repository is much easier than frontend :)
@regiskuckaertz, looking [here](https://github.com/guardian/commercial-templates/blob/jn-switch-preview-port/src/_shared/js/messages.js#L153) could we not remove the need for `DevMode` by just using `location.port`?
> Change PORT for running locally

- clean.js
- package.json
If the `build` task fails, then it fails silently. Instead of fixing that, I just wrote a `clean` task that can be run before running `build`, thus making it obvious when the build fails - i.e. an empty target folder - rather than having the old files squatting there and deceiving you into thinking it has correctly built.
> Provide a method to clear the build directory

- src/_shared/js/dev.js
It didn't really seem to fit anywhere, so I created `dev.js`. This can be used to wrap any uses of `host` to fetch from frontend.
> Provide method for altering the port for running with frontend.

- README.md
Thought this might be useful for testing components that are built dynamically and which require running frontend.
> Add CORS instructions for testing preview locally.

- src/_shared/scss/_core.scss
- src/_shared/scss/_helpers.scss
- src/fabric/index.html
- src/fabric/index.scss
This works:
Introducing two important utility classes:
- `gs-container` will create a 100% container which has a content area matching the content area of the website and left-/right-padding that will fill the remaining space
- `u-root` sets the element as a containing block, i.e. it applies `position: relative`
> Fabric native

- src/_shared/js/messages.js
`window.innerHeight` is the height of the _viewport_, which may not necessarily be equal to the height of the _creative_, since it relies on the geometry of the parent iframe element. Instead we'll resort to computing the geometry of the `BODY`, which is a good proxy for our needs.
Not happy with how rollup deals with the `...` spread operator inside arrays, so I switched to a more conventional `concat` op.
(Of course, after merging, all creatives must be re-generated and manually uploaded in DFP. We need a command line to do that 😭 )
> Improve resizeIframeHeight

- preview/src/js/components/Preview.js
- src/_shared/js/config.js
- src/_shared/js/messages.js
- src/soulmates/index.js
This PR accomplishes two things
1) Removes the reference to `[%SubFeed%]` in `config.js`, which otherwise causes DFP to freak out when rendering anything other than Soulmates.
2) Makes the querying of `frontend` JSON endpoints consistent by using parameters rather than inspecting the path. Inspecting the path was probably slightly more straightforward but... CONSISTENCY.
@Ap0c
> Removes buggy use of DFP variable in  and uses parameters for API query.

- package.json
- src/_shared/js/images.js
- src/capi-single-paid/index.js
- src/capi-single-paid/test.json
- src/capi-single-supported/index.html
- src/capi-single-supported/index.js
- src/capi-single-supported/index.scss
- src/capi-single-supported/test.json
This extends the work done in https://github.com/guardian/commercial-templates/pull/43. Given the different styling it was simpler to separate supported and paid-for into separate DFP templates.
This PR also fixes issues with the CAPI paid-for single such as typos (! 😱 ) and the added complexity with sourceset. 
cc @regiskuckaertz @JonNorman @Ap0c
> CAPI Merchandising Single - Supported Template

- src/capi-single-paid/index.html
- src/capi-single-paid/index.js
Small fix to reflect the 3 variants of the glabs landing page. This is only relevant for CAPI single paid. Following earlier work on the front-end controller, the JS checks edition data and decides relevant logo link.
cc @regiskuckaertz
> Incorporate 3 variants of Glabs landing page in Capi Single Paid

- src/capi-single-paid/index.html
- src/capi-single-paid/index.js
- src/capi-single-paid/index.scss
- src/capi-single-supported/index.js
- src/capi-single-supported/index.scss
- WebFonts were being retrieved but not rendered on CAPI supported. This was because the page had to wait for the HTML to be rendered
- The button on Supported was not the correct style - added background and border color
- The popup tag on CAPI paid was incorrect, adding correct tag and specific styling fixed this.
cc @regiskuckaertz
> Small CSS tweaks to CAPI Single templates

- src/_shared/js/capi-multiple.js
- src/capi-multiple-paidfor/index.scss
- src/capi-multiple-supported/index.scss
Minor fixes noticed in PROD testing:
- JS selector was using a class that got renamed, fixed this (didn't show up locally for some reason).
- Updated text colouring to match pre-existing capi ads (think this was previously inheriting from `body`, no longer possible in iframe)
@regiskuckaertz @annebyrne @JonNorman @Calum-Campbell
> Fix Capi Prod Errors

- lib/js.js
- src/_shared/js/dom.js
- src/_shared/js/messages.js
- src/capi-single-supported/index.html
- src/capi-single-supported/index.js
**Bug**
Chrome has a bug whereby requestAnimationFrame does not work with empty elements. 
Previously the CAPI Single Supported template had a single aside tag in its HTML, and the template was rendered by the javascript for simplicity due to header and body structure.This meant that the element had no height associated with it. 
**FIx**
The population of CAPI data in the header and the body of the component has been separated into 2 different functions and the HTML includes more content prior to JS rendering.
There have been a few small changes to shared JS files.
**Screenshots**
Firefox:
Chrome:
cc @guardian/commercial-dev @regiskuckaertz
> Fix for Chrome bug on CAPI Supported Single Template

- build.js
This is the standard behaviour for all our ads, plus it will allow us to track clicks more consistently.
> Open links in a new tab

- src/_shared/js/ads.js
- src/_shared/js/capi-images.js
- src/_shared/js/capi-multiple.js
- src/capi-single-paid/index.js
- src/capi-single-supported/index.js
- src/glabs-native-traffic-driver/index.html
- src/glabs-native-traffic-driver/index.js
- src/glabs-native-traffic-driver/test.json
- Modifies the Glabs Native Traffic Driver to pull its content from cAPI.
- Added optional DFP overrides for content.
- Modified `capi-images` module to allow usage from multiple templates.
- Updated capi-single and capi-multiple to use modified images module.
- Pulled method for setting glabs link out into `ads` module, for more general usage.
There was also a corresponding endpoint added to frontend in [this](https://github.com/guardian/frontend/pull/14606) PR.
@JonNorman @Calum-Campbell @annebyrne @regiskuckaertz
> Traffic Driver cAPI Integration

- src/manual-inline/index.html
Merchandising have asked for the CTA button to have a variable message in it. This change updates the manual inline.
The Omniture ID also needed updating.
@JonNorman @regiskuckaertz
> update the manual inline to include changeable CTA

- src/fabric-expandable/index.js
- src/fabric/index.html
- src/fabric/index.js
- src/fabric/index.scss
Does ~~three~~ four things:
- uses the fixed/parallax background messages for smooth scrolling effects
- uses `onViewport` to get the correct dimensions of the parent frame, rather than a media query
- adds support for animation on the second layer
- sends the maximum height for the background image in the parallax mode
> Apply fixes to Fabric Native

- build.js
- src/fabric-expandable/index.js
- src/fabric/index.js
The fixed/parallax scroll effects had some problems that the DAP team reported. I fixed these in this PR.
- use media queries to detect mobile/tablet environments
- unify background message
- simplify persistent listeners logic
This PR is linked to [this one](https://github.com/guardian/frontend/pull/14806).
> Fixes to the Fabric and Fabric expandable templates

- lib/css.js
- package.json
- src/_shared/js/messages.js
- src/_shared/scss/_advert.scss
- src/travel/test.json
@ScottPainterGNM reported many issues in the native travel component that were all related to the same causes:
1- the CSS was not post-processed to include prefixes for older browsers
2- the promise waiting for images to load never resolved, resulting in ads that appeared cut through
This PR addresses these issues, which are shared across all templates.
> Layout fixes in Safari, IE et al

- build.js
- lib/build.js
- lib/css.js
- lib/html.js
- lib/js.js
- package.json
- src/_shared/scss/_core.scss
- src/_shared/scss/_helpers.scss
- src/fabric/amp/index.html
- src/fabric/amp/index.js
- src/fabric/amp/index.scss
- src/fabric/app/index.js
So, AMP is very specific in that:
- we can't use JavaScript: this severely limits the scope of each template to be essentially empty HTML fragments with DFP placeholders
- we can't use `style` attributes: that means moving all the style-related variables into the CSS
- AMP is for mobile only so all the desktop stuff can go away
- Finally, the `!important` keyword is forbidden in AMP... I don't know why
As a result I had to change the build process, which is the point of this PR. It also adds a Fabric for AMP for testing purposes.
(As a corollary, a much better build process will be written at some point in the future. It is good enough now. For example, we could use UNCSS to remove all the unnecessary styles for a specific template.)
> Making place for AMP creatives

- src/manual-inline/web/index.html
The manual inline component did not abide _by the law_ that the class names in `adverts` components must be pluralised..
> Fix misspelled class name

- src/_shared/scss/_adverts-books.scss
- src/books/test.json
The cards within the books native component currently have no maximum height, which can lead to inconsistent looking book covers.
This PR provides a maximum height to the cards and centres them within the image containers.
**Non prominent (old)**
**Non prominent (updated)**
**Prominent (old)**
**Prominent (updated)**
@guardian/commercial-dev
> Fix the height of the books component and make them centred

- src/_shared/js/capi-multiple.js
- src/_shared/scss/_adverts-capi.scss
- src/capi-multiple-paidfor/test.json
- src/capi-multiple-paidfor/web/index.scss
On mobile, we should only show one article with a pic, followed by two without beneath it.
@ScottPainterGNM
> CAPI multiple: Update mobile breakpoint design to fit the spec

- src/blended/web/index.js
- src/books/web/index.html
- src/books/web/index.js
- src/capi-multiple-paidfor/web/index.html
- src/capi-multiple-supported/web/index.html
- src/capi-single-paid/web/index.html
- src/capi-single-paid/web/index.js
- src/capi-single-supported/web/index.html
- src/capi-single-supported/web/index.js
- src/gimbap-richmedia/web/index.html
- src/gimbap-simple/web/index.html
- src/gimbap/web/index.html
- src/glabs-native-traffic-driver/web/index.html
- src/jobs/web/index.html
- src/jobs/web/index.js
- src/manual-inline-event/web/index.html
- src/manual-inline-event/web/index.js
- src/manual-inline/web/index.html
- src/manual-multiple-hosted/web/index.html
- src/manual-multiple-membership/web/index.html
- src/manual-multiple-soulmates/web/index.html
- src/manual-multiple/web/index.html
- src/manual-single/web/index.html
- src/soulmates/web/index.html
- src/soulmates/web/index.js
- src/travel/web/index.html
- src/travel/web/index.js
As a general rule, merchandising components open links in the current window.
> Open links in current window in merchandising components

- src/blended/web/index.js
Small fix where masterclass images were not showing up because of a dangling `${location.protocol}`.
> Remove protocol from image path

- src/_shared/js/capi-multiple.js
- src/capi-multiple-hosted/test.json
- src/capi-multiple-hosted/web/index.js
Removes some hosted-specific code from the shared js.
DFP doesn't let you save if there are variables in the html that are not defined for that template. Only the Hosted one uses kickers.
> Capi multiple fix

- src/_shared/js/capi-multiple.js
- src/_shared/scss/_adverts.scss
- src/capi-multiple-paidfor/test.json
- src/capi-multiple-paidfor/web/index.html
- src/capi-multiple-paidfor/web/index.js
I expect AdOps to pay due diligence and not provide both a container logo and a card logo.
> CAPI multiple: Add an optional brand logo to each card

- src/_shared/js/creatives.js
- src/manual-multiple-membership/web/index.js
- src/manual-multiple-soulmates/web/index.js
- src/manual-multiple/web/index.js
Pass parameters into cleanupButtons function so that the number of DFP variables can differ.
Soulmates now only has 3 cards (since https://github.com/guardian/commercial-templates/pull/125), so trying to save the new template with `[%Offer4LinkText%]` in the js didn't work.
> Fix for Soulmates js

- src/manual-inline-book/web/index.js
This is because the ISBN is sometimes defined as a property of the page in composer, available as `config.page.isbn` on frontend. When available, it will be passed in as a slot targeting value.
> Allow slot-injected ISBN

- src/_shared/js/capi-multiple.js
- src/_shared/js/hosted-colours.js
- alter the colour contrast algorithm to be consistent with hosted pages when colour lightness === 0.5
- disable multi-logos functionality for hosted - no designs for this yet
> Hosted container fixes

- src/manual-multiple-soulmates/test.json
- src/manual-multiple-soulmates/web/index.html
- src/manual-multiple-soulmates/web/index.scss
Change which values we expect for Number of Cards to ensure backwards compatibility with existing creatives
related to https://github.com/guardian/commercial-templates/pull/125
> Manual multiple soulmates - fix

- package.json
- src/_shared/scss/_adverts-capi.scss
- src/_shared/scss/_adverts.scss
- src/capi-multiple-paidfor/web/index.js
- src/capi-multiple-paidfor/web/index.scss
Alternative version of https://github.com/guardian/commercial-templates/pull/131. 
This one relies on flexbox support to make the title accommodate the badge. As a bonus, this version of the title is greedy and will fill the space if the badge is gone.
- Add missing dev dependency (nodemon) so that `npm run preview` doesn't throw an error
- Better positioning of the paidFor label at all breakpoints
:grin: Making our natives match frontend: https://github.com/guardian/frontend/pull/16062
__________
____________
____________
> Improve the layout of paid containers (with Flexbox)

- package.json
- src/capi-multiple-paidfor/web/index.js
- src/capi-multiple-paidfor/web/index.scss
- Add missing dev dependency (nodemon) so that `npm run preview` doesn't throw an error
- Better positioning of the paidFor label at all breakpoints
:grin: Making our natives match frontend: https://github.com/guardian/frontend/pull/16062
__________
____________
____________
> Improve the layout of paid containers

- src/_shared/scss/_adverts-soulmates.scss
Move some CSS around  - the `width: initial; height: initial;` should only be applicable to the class `.icon--soulmates-join`, since we don't want these stlyes applied to all SVGs in the soulmates component (the arrows have reeeally large initial dimensions)
[Commercial Trello card](https://trello.com/c/Lp72MM8T/51-soulmates-component-is-broken-in-edge-14)
Cautiously optimistic that this will fix the Microsoft Edge 14 arrow issue
> Fix the arrow size issue on Edge 14

- src/capi-multiple-paidfor/app/app-capi-multiple.js
- src/capi-multiple-paidfor/app/index.html
- src/capi-multiple-paidfor/app/index.js
- src/capi-multiple-paidfor/app/index.scss
This is very similar to the web capi-multiple-paid-for template, but without waiting to get the iframe ID.  I've tested it on iOS.
> Make app-specific capi-multiple-paid-for template

- src/google/web/index.scss
By moving the logo element directly below the image in DFP we can then float it right in line with the headlines and achieve our desired design instead of using absolute positioning. Winner!
In DFP - https://www.google.com/dfp/59666047?gsessionid=ptJVasseHTklzLwxNqEovknfodaYmNxq#delivery/CreateNativeAdFormatAndStyle/nativeStyleId=109638&creativeTemplateId=10004520
> Amend logo to be non-absolute

- src/capi-multiple-supported/web/index.html
This fixes the clickthrough link for the CAPI multiple-supported by template.
> Add guardian.com to CAPI multiple-supported by template.

- src/_shared/scss/_core.scss
- src/glabs-inline/test.json
- src/glabs-inline/web/index.scss
- src/glabs-left/web/index.js
- src/glabs-left/web/index.scss
This PR does two things:
1. Fixes the width of the images at different breakpoints. Trying to make the image resize as the breakpoints change is a nightmare, especially considering differently proportioned images.
2. Adds `mq` breakpoint mappings that represent the width of the iframe at those breakpoints when in an article. When using media queries within an iframe, it is the size of the iframe that is queried, not the size of the device.
> Fix the widths of glabs-inline images; it makes everything simple.

- src/_shared/scss/_core.scss
- src/glabs-inline/web/index.html
- src/glabs-inline/web/index.scss
- src/glabs-left/web/index.html
- src/glabs-left/web/index.js
- src/glabs-left/web/index.scss
These are the final* changes to this before the test is run. They are:
1. Using a single anchor tag that overlays the entire container rather than linking individual component elements.
2. Add darken on hover, to match behaviour of inserts on frontend e.g. rich-links as well as cursor style.
3. The iframe for the glabs-left style will resize itself again. I this was removed whilst debugging a different styling issue.
*assuming we don't get drastic level of complaints about something or other.
> GLabs Traffic Driver Style updates

- preview/src/js/components/Preview.js
- src/_shared/js/messages.js
- src/fabric-custom/test.json
- src/fabric-custom/web/index.html
- src/fabric-custom/web/index.js
- src/fabric-custom/web/index.scss
A new Native style that wraps a third party script in order to provide the following behaviour:
- Provides the Guardian web fonts to the iframe
- Adds the Advertisement label
- Resizes the iframe once it is done.
It achieves this by either fetching and inserting a third party tag or by fetching the assets from a specified S3 bucket and adding the `index.html` fragment into the page.
@guardian/commercial-dev
> Create a new template for wrapping around third-party creatives.

- style-sync/src/main/scala/commercialtools/stylesync/DFP.scala
Accidentally removed the `trait Logging` from `StyleSync.scala`, this is still required by `DFP.scala` and so has been added back in there.
> Fixing accidental removal of Logging trait.

- lib/js.js
According to these [options]( https://github.com/mishoo/UglifyJS2#compress-options), we can disable constant expression evaluation, things like:
```
'[%ShowLabel%]' === 'true'
```
We want uglify to ignore this, because the macro will be expanded much later, inside DFP.
> Do not evaluate constant expressions during uglify

- src/capi-multiple-nologos/test.json
- src/capi-multiple-nologos/web/index.html
- src/capi-multiple-nologos/web/index.js
- src/capi-multiple-nologos/web/index.scss
- New template for testing b2b article promotion
- Multiple articles 'supported by' different clients, without multiple logos
> Add new template for capi-multiple supported

- src/mobile-revealer/web/index.js
This PR achieves two things:
1) Fixes a bug where the returned values from `getIframeId` were being passed into `resizeIframeHeight`, resulting in weird behaviour.
2) Removes `once` from the background update, given that `frontend` now supports refreshing a background image when the viewport changes.
> Fix resizing in mobile revealer template

- src/fabric-expandable/web/index.js
- src/fabric/web/index.js
At the moment, if a background image is not provided then the function returns without setting the background colour.
If a background image is not provided, but a background colour _is_ provided, then we should honour this. This PR alters the behaviour to reflect this.
> Fabrics: always set the background colour, if provided.

- src/_shared/scss/_adverts-capi.scss
Turns out when I adjusted the flex- for the CAPI template I didn't check how it looked at tablet breakpoint. Awkward.
- Added a media query to the capi CSS to change flex-direction at tablet (not desktop) breakpoint so the header div changes from:
to
> Update flex-direction for CAPI template on tablet

- src/epic/test.json
- src/epic/web/index.html
- src/epic/web/index.scss
__Changes:__
- Epic CSS fix. Change taken from [#19891](https://github.com/guardian/frontend/pull/19891).
- DFP click through macro added to support link - this allows us to track click-through rate in DFP
__Note:__
The Epic HTML and CSS files generated by `npm run build` have already been uploaded to the DFP line item `contributions/test:AcquisitionsEpicNativeVsDfpV2/variant:dfp`. Testing locally has verified the link is valid with the click-though macro.
> Epic tweaks

- src/_shared/js/capi-multiple.js
- src/capi-multiple-hosted/test.json
- src/capi-multiple-paidfor/test.json
- src/capi-multiple-supported/test.json
Intermediate step is solving a missing label issue. It seems that some content does not have or pass through active sponsorship data. So this PR adds a sanity check to see if there is branding to be applied, before adding the labels.
BEFORE:
AFTER:
I would rather use `const` as the default anyway and avoid rebinding as much as possible
Some of the test campaigns have expired so switching to alternatives
> Hide the branding labels on capi-multiple if the branding is missing 

- src/fabric-video/web/index.html
- src/fabric/web/index.html
In the Fabric Video and Fabric templates add in a Viewability, Research and Tracking pixel. Also remove an unnecessary cachebuster that gets added in the tag itself, to avoid duplication.
> Add pixel fields to Fabric Video and Fabric templates

- style-sync/build.sbt
- style-sync/src/main/scala/commercialtools/stylesync/DFP.scala
- style-sync/src/main/scala/commercialtools/stylesync/StyleSync.scala
DFP is now called AdManager...
This breaks a lot of things in the API since the version on which we were relying is now sunsetted.
This change will make the StyleSync tool work once more!
Thank the fabulous @JonNorman for the fix 🙏 🙇 🎉
> Fix broken util task by updating DFP API references

- src/carrot/web/index.scss
- src/parallax-mpu/web/index.html
- src/parallax-mpu/web/index.js
When updating to the latest version of Chrome, it caused the parallax functionality of the Parallax MPU native format to break. The background image was no longer visible. Changing the scroll type to parallax instead of fixed, and covering the background image instead of containing fixes the issue.  
NB: it seems a bit jerky on mobile but it's a quick fix for now for a big Google campaign going live ASAP. Mobile jerkiness will be a separate PR.
> Fix parallax MPU bug

- build.js
This updates the polyfill address used within templates;
- We now use `v3` instead of `v2`
- Caching issues have been fixed on assets.guim.co.uk
`clearCache` has also been added; this isn't a requirement however it's good to know how to bust the cache in scenarios where we need to. (Which we have had to on polyfill!)
> Update polyfill address and version

- .stylelintrc.json
Sometimes we have empty source `.scss` files that need to be included. This adds a message requiring people to add a comment  to these files in order  for them to pass stylelint checks.
> Add custom message to handle empty source files.

- src/page-skin/test.json
- src/page-skin/web/index.js
- src/page-skin/web/index.scss
- Currently 'Skin for front pages' templates is just living in Ad Manager. As an attempt to version control it we copied it in commercial-templates repo.
- Also adding a postMessage event to send an event to the frontend that the pageskin has been rendered
> Add Page-skin template into commercial templates & introduce event

- src/truskin-page-skin/web/index.js
This is a fix for truskins which went out of sync on slow networks. The truskin was not working as expected because the fabric & the truskin weren't loaded at the same time. Sending an event to the frontend from the commercial template makes sure both are rendered before we do the calculations for repositioning them
Co-authored-by: Josh Buckland <buck06191@gmail.com>
> Fix truskins on slow networks

- src/_shared/scss/_adverts-climate.scss
- src/_shared/scss/_palette.scss
- src/manual-multiple/web/index.html
- src/manual-multiple/web/index.scss
- src/manual-single/web/index.html
- src/manual-single/web/index.scss
Australian team has requested to create a new manual template with the Climate Pledge colours to be used to keep the climate pledge message going in the wake of bush fire crisis, and they thought a merch slot would be worth testing.
> Add climate colours to manual multiple & manual single templates

- src/_shared/js/messages.js
- src/glabs-native-traffic-driver/web/index.js
Native traffic drivers were failing to resize in Australia. This seems to be because an explicit return statement was required as is now seen on [line 110 of `src/_shared/js/messages.js`](https://github.com/guardian/commercial-templates/compare/native-traffic-fix-for-australia?expand=1#diff-464152bc8d3f5065a5d49485bb558a3bR110).
Adding this in appears to have fixed the problem, which has been tested using browserstack against a machine in Australia as well as against UK machines.
> Native traffic fix for australia

- src/interscroller/test.json
- src/interscroller/web/index.html
- src/interscroller/web/index.js
- src/interscroller/web/index.scss
For the Interscroller format the creative is injected further up the page via frontend and the iframe height was not been set, which was causing an issue with the activeView impression firing.
Test format setup at 
https://admanager.google.com/59666047#creatives/custom_native_style/detail/styleid=400193
Adtest on production
https://www.theguardian.com/fashion/2020/nov/04/put-my-own-makeup-on-for-the-first-time?dcr=false&adtest=ArmaniEAGent2
Should be able to see the activeView event firing.
Needs to be tested on mobile devices, but I can't see any potential risks.
> Sw viewabiltiy tracking issue

- src/_shared/scss/_adverts-brand-new.scss
- src/manual-single/test.json
- src/manual-single/web/index.html
- src/manual-single/web/index.scss
We've created a `brand-new` tone for the `manual-single` template following the specifications as requested by the BRR team. This will allow them to test and learn about contributions and digital subscriptions.
**Before**
**After**
> Added brand-new tone

- src/capi-multiple-paidfor/web/index.html
Remove the `[%TrackingId%]` from CAPI Multiple Paid For native ads.
This parameter is not provided via the native format in GAM - this causes an error when attempting to publish the template style since it expects a Tracking Id and none is provided.
> Remove tracking id from Capi Multiple Paid For templates

- src/_shared/scss/_adverts.scss
- src/manual-multiple/web/index.html
This PR fixes a layout issue where the header of native adverts in merchandising slots does not align with sections on the rest of the website. 
The fix is to increase the the width of the header by half a gutter width (and an additional pixel to account for the border drawn by other sections). Additionally the spacing in the advert row and body has been adjusted to account for the change in width of the header.
| Before      | After      |
|-------------|------------|
| ![Screenshot 2021-08-19 at 14 47 44](https://user-images.githubusercontent.com/8000415/130080143-b7c5f2dd-55c3-42c0-831e-64df065822d2.png) | ![Screenshot 2021-08-19 at 14 47 54](https://user-images.githubusercontent.com/8000415/130080192-9767df12-ba8e-4a02-91c9-1e2d8f028a8b.png) |
Note that this does not affect paid for …
> Update native ad header alignment

- src/_shared/js/events-multiple.js
- src/events-multiple/web/index.html
Move the meta text associated with each card from a child of the title text to sibling. This has the effect of not applying header styling to the meta text.
Meta text shouldn't have the advert title styling applied. If this is desired the text can be included as part of the title from within Ad Manager.
> Fix meta text for Events Multiple templates

- src/fabric-custom/test.json
- src/fabric-custom/web/index.html
- src/fabric-video-expandable/test.json
- src/fabric-video-expandable/web/index.html
- src/fabric-video/test.json
- src/fabric-video/web/index.html
- src/fabric/test.json
- src/fabric/web/index.html
Historically we have versions of the main Fabric native styles that have an extra open field after Adops requested it to add Moat JS tracking tags.
https://admanager.google.com/59666047#creatives/custom_native_style/detail/styleid=278072
Adops now use Moat and other JS tracking tags with more frequency that it makes sense to just add the extra field to all the standard Fabric templates and just have the one template.  
test.json has an example tracking tag from Adops, should see the tag render in the preview, appended to the foot of the template.
Currently we sometimes have to re upload creatives to the Moat version when tracking comes over from client. With the extra field as standard it should cut down on this and the extra time spent.
> Adding an extra tracking field within fabric templates for adops to use JS tracking tags

- .eslintrc.cjs
- package.json
Consolidate plugins property in `.eslintrc.cjs` – there are currently two entries for this property, which causes ESLint to fail with the message:
> invalid: 'svelte3/svelte3' was not found
For convenience, I've also made the following changes:
- added a `lint:fix` script that automatically fixes lint errors detecting to ESLint, if possible
- ignored `legacy/` code from ESlint run – mainly because it finds so many errors, and fixing them seems lower priority right now. Happy to discuss!
Run ESLint:
```sh
$ npm run lint
```
Observe that the error message no longer appears and ESLint run completes successfully – albeit with legitimate linting errors we can fix later.
> Consolidate plugins in eslint config

- package-lock.json
- package.json
- src/app.html
- src/routes/csr/[template].json.ts
- src/routes/ssr/[template].json.ts
- src/routes/templates.json.ts
- svelte.config.js
- vite.config.js
- upgrades to the latest versions of `@sveltejs/kit` and `vite`. This exposes vite to the developer, as opposed to hiding it behind the svelte-kit CLI.
The following scripts still work:
```sh
$ npm run dev
$ npm run build
$ npm run preview
```
> Upgrade sveltekit and vite

- package.json
Removes the `rsync` directory jiggling part of the build script as it no longer appears to be necessary.
Deploy Svelte-kit preview via
```sh
$ npm run deploy
```
Open:
https://guardian.github.io/commercial-templates/
> Remove rsync dir jiggling from build script

- legacy/src/interscroller/web/index.js
Pass an identifier to `getIframeId` so that frontend will add an appropriate classname.
We need this class to target the interscroller ads with specific css, an example added here https://github.com/guardian/dotcom-rendering/pull/5527
> pass interscroller identifier to getIframeId

- legacy/package-lock.json
- legacy/package.json
Bumps nodemon from `2.0.7` to `2.0.19`. This removes the dependency on [got](https://www.npmjs.com/package/got) which is causing [this security alert](https://github.com/guardian/commercial-templates/security/dependabot/24)
> Bump nodemon from 2.0.7 to 2.0.19

- .github/workflows/gh-pages.yml
Add a github action for automated pages deployment so that https://guardian.github.io/commercial-templates/ is always up to date :)
Will require changing the repo setting to use actions for pages deployments.
> Add a github action for automated pages deployment

- legacy/src/_shared/scss/_adverts.scss
- legacy/src/_shared/scss/_hosted.scss
Update to the background colour of the merchandising slots to be consistent with the DCR palette. This should eliminate the colour difference between div and merchandising slots currently visible on articles rendered by DCR.
> Update background colour to match DCR palette

- legacy/src/_shared/js/capi-multiple.js
- legacy/src/_shared/scss/_adverts-capi.scss
- legacy/src/capi-multiple-paidfor/app/app-capi-multiple.js
Remove the trailing `/` added to kickers via CSS, and add a line-break after the kicker (when a kicker is rendered).
This brings the kicker styling into line with the new designs for web -- see [DCR Issue #6943](https://github.com/guardian/dotcom-rendering/issues/6943)
Co-authored-by: Anna Beddow <anna.beddow@guardian.co.uk>
Co-authored-by: Jake Lee Kennedy <jake.kennedy@guardian.co.uk>## What does this change?
We have tested this locally using the `preview` app. The commercial team may want to try a test build in GAM before deploying.
**nb.** We may want to hold off on deploying to PROD until the corresponding Frontend/DCR changes have been deployed.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
- …
> Remove trailing '/' from kicker

- legacy/src/_shared/scss/_adverts-fabric.scss
- legacy/src/fabric-custom/web/index.scss
- legacy/src/fabric-video/web/index.scss
- legacy/src/fabric/web/index.scss
On Firefox, the default browser margin means that fabric ads display with space between the ad label and top of the page (see image), which they shouldn't. This PR sets the margin to zero to ensure that fabric ads display as expected on Firefox.
> Fix fabric margins on Firefox

- legacy/src/capi-single-paidfor/web/index.html
The capi single paid-for template was broken when the first capi entry had a video associated with it. This is because the videoIcon was undefined, due to speech marks breaking up the variable assignment. Adding backticks to the var declaration ensures the video icon is correctly defined, and that the creative can be rendered.
VideoIcon was defined like this:
With this PR it becomes:
Creative doesn't load any content:
Creative loads correctly:
> Use backticks to fix unexpected token error

- legacy/src/programmatic-dmpu/test.json
- legacy/src/programmatic-dmpu/web/index.html
- legacy/src/programmatic-mpu/test.json
- legacy/src/programmatic-mpu/web/index.html
Adops often have to added JS tracking tags to creatives. Currently Fabrics have this field, but the two templates programmatic ops use( programmatic-mpu and  programmatic-dmpu) do not. This changes brings those templates inline with the Fabrics.
NPM run preview 
check the programmatic-mpu  and programmatic-dmpu preview in dev tools. Should be able to the test JS tag.
> JS tracking field - added at request from Programmatic ops

- src/lib/messenger.ts
- src/templates/ssr/interscroller/index.ts
Adds a parameter called videoSource to the interscroller template. This allows the a video to be added to the native interscroller template. If defined, the commercial code will create and add a video html tag to the interscroller ad.
For video interscrollers, the backgroundImage will display behind the video and will act as a fallback if the video fails to load, so it should still be defined for these ads.
Demo video:
https://github.com/guardian/commercial-templates/assets/108270776/c164922d-da41-40d3-9992-cbcb3a4e278b
> Add video source parameter to interscroller

- src/templates/csr/capi-multiple-paidfor/index.svelte
- src/templates/csr/capi-multiple-paidfor/test.json
The SeriesUrl variable has been updated to SeriesURL to match the native format. This means the native style should now update automatically via the GitHub Action. It failed on the previous merge because of this variable name mismatch.
> Update SeriesUrl variable name to match format

- src/templates/components/CapiCard.svelte
Adds the clickMacro to the card href. At the moment the cards aren't linking to articles properly on the CAPI Multiple PaidFor template on the live site. Adding this clickMacro should resolve this.
You can see in the image below that the link currently opens within the ad iframe.
> Add clickMacro to card href

- src/templates/components/ManualCard.svelte
Manual cards currently navigate to links inside the iframe when clicked, when they should be using the whole window (see GIF). Adding target="_top" should resolve this.
> Add target="_top" for manual cards

- src/templates/components/CapiCard.svelte
Adds a min-height of 80px for images in the Capi Card. Having observed different breakpoints, I can't see any images loading with a height of less than 96px, so this should be a safe value.
We noticed that on the first page load for a CAPI Multiple PaidFor ad on the site, the iframe doesn't load in a big enough size for the ad to show. On subsequent page views it then seems to behave as expected. (Open a lifestyle article in incognito mode to replicate this). The legacy template set min-heights on the images, so we're adding a min-height to images to see if this is the cause of the behaviour or not.
Example of iframe not loading to correct size:
> Set min-height for CapiCard images to 80px

- src/lib/Previews.svelte
- src/templates/components/CapiCard.svelte
- src/templates/components/Resizer.svelte
- src/templates/components/SetHeightResizer.svelte
- src/templates/csr/capi-single-paidfor/index.svelte
- src/templates/csr/events-multiple/index.svelte
- src/templates/csr/manual-multiple/index.svelte
A number of changes:
- Changes the Resizer message from `set-ad-height` to `resize` as we think Messenger wasn't receiving the set-ad-height message in a valid form and so no resize took place
- Keeps the old Resizer logic in a renamed component. We don't want this update to negatively affect existing templates without the slow network resize bug, so we've kept the old logic for the templates I didn't test on GAM. We can revisit this in future but it's more important to get the bug fixed now.
- Adds local handling for the resize post message so that Preview containers resize correctly
- Changes the dividing line heights for the CAPI Multiple PaidFor template as I noticed they were a bit off when testing. Images below.
I've tested this by throttling the network connection and using a test …
> Fix Resizer bug and minor style tweak

- legacy/src/_shared/js/dom.js
- src/lib/Previews.svelte
- src/lib/capiMultiple.ts
- src/lib/types/capi.ts
- src/templates/components/CapiCard.svelte
- src/templates/components/CapiHostedCard.svelte
- src/templates/components/HostedHeader.svelte
- src/templates/csr/capi-multiple-hosted/ad.json
- src/templates/csr/capi-multiple-hosted/index.svelte
- src/templates/csr/capi-multiple-hosted/test.json
- src/templates/csr/capi-multiple-paidfor/index.svelte
- src/templates/csr/capi-single-paidfor/index.svelte
- src/templates/ssr/interscroller/index.svelte
- src/templates/ssr/manual-single/index.svelte
Converts the CAPI Multiple Hosted template to Svelte. Each card is represented by the CapiHostedCard component. This is similar in many ways to the CapiCard component, but also has several key differences as well, so I have left them as two separate components for now.
- From the initial template, "kicker" and "numberOfElements" are no longer used, so I have removed them.
- The gaps between cards are now more consistent
- Adds a slight opacity on hover to give visual feedback to user
- Cards take up a bit more height between breakpoints, making using of responsive design
| Legacy | Svelte |
| - | - |
| ![legacy1] | ![svelte1] |
| Legacy | Svelte |
| - | - |
| ![legacy2] | ![svelte2] |
| Legacy | Svelte |
| - | - |
| ![legacy3] | ![svelte3] |
| Legacy | Svelte |
| - | - |
| ![legacy4] | …
> Migrate CAPI Multiple Hosted template to Svelte

- src/templates/ssr/fabric-custom/index.svelte
Creative opening url in the same iframe, adding base with a target of _blank is needed.
Running preview locally clicking banner will open a new window.
> FIX: Creative opening url in the same iframe

- src/templates/ssr/fabric-custom/ad.json
In some custom fabrics we run JS. On legacy it runs, but on the svelte version it doesn't.
Can be tested locally by switching dapAssets parameter to a custom with JS
Example 
DAP_Hilton_standard_dec23
That will start animating in legacy, but not in the svelte preview because the animate class is not added.
Script tag is being added and doesn't look malformed.
> Preventing deployment by removing ad.json to look at JS issue

- src/lib/capiMultiple.ts
The advertiser logo was missing from the hosted template. This is because we were using the [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) operator. The left hand operand should be `null` or `undefined` to return the right hand side. An empty string is falsy but not null, so we were returning an empty string as the logo. I've switched to using a ternary operator, which checks for a falsy value instead.
> Amend logic for hosted advertiser logo

- src/lib/Code.svelte
At the moment, on each template page we show the full HTML and CSS for the template underneath. This is left over from when we had to manually copy the HTML and CSS into the templates in GAM. Now that we don't need to do that, it looks nicer to hide it by default, but it's still easily accessible behind a button.
This change is also a pre-requisite for visual regression testing, as having the HTML and CSS written out is a very common cause of false positives.
> Don't show HTML and CSS by default

- .eslintrc.cjs
- src/templates/components/Pixel.svelte
- src/templates/ssr/fabric-custom/index.svelte
- src/templates/ssr/fabric-custom/index.ts
The `Pixel` component won't work in an SSR component because the [`isValidReplacedVariable`](https://github.com/guardian/commercial-templates/pull/382/files#diff-112bfaccb078632e0383ee5103c3360f7ed59e87ebfc5c543079a469287f88a1L7) used there will cause the `img` element to never render during SSR.
I've moved the pixel code to the `index.ts` and added a guard to the `Pixel` component to prevent it being used in an SSR component in future.
> Fix fabric-custom tracking pixel

- package.json
- scripts/deploy/Pipfile
- scripts/deploy/Pipfile.lock
- scripts/deploy/deploy.py
The deploy script is using a deprecated version of the DFP API, so the deploy action is currently failing. This PR updates the DFP API to the latest version, so we should be good for the next year or so.
Also adds `"prepare": "svelte-kit sync"` to the `package.json`. This makes sure that the `.svelte-kit/tsconfig.json` exists so that the root `tsconfig.json` can extend it while running github actions. This solved a GHA error I got on the PR.
> Upgrade DFP API version

- src/templates/csr/public-good-test/ad.json
- src/templates/csr/public-good-test/index.svelte
This PR adds a new test for Public Good. A new template named `public-good-test` is created with the new integration as requested by US and Public Good. Check [ticket](https://trello.com/c/MR25vjOO/2949-create-a-new-test-template-for-public-good) for more details and to check the new integration. 
I added the `nativeStyleId` for this native test https://admanager.google.com/59666047#creatives/native/native_style/detail/style_id=844854&tab=ad_settings but this `id` will be changed when we have a PROD Public Good with this new template. 
Public Good is served in the `article-end` slot when Reader Revenue epic doesn't show up and it's only served in US so using a VPN is a must to test and add at the end of the article url `?adtest=comm-dev-public-good-test`
- The new data attributes which …
> Create new test template for Public Good

- .eslintignore
- .github/workflows/visual-regression.yml
- playwright.config.ts
- playwright/fabric-custom.test.ts
- playwright/manual-multiple.test.ts
- playwright/manual-single.test.ts
- scripts/analyse-visual-results.js
Updates the way that visual regression testing works to improve the developer experience. The visual regression test action no longer fails if there are visual changes, to reflect the fact that these may be intentional. Instead, a comment is added to the pull request to indicate if tests are failing, and for which templates.
> Add PR comment with visual test results

- src/templates/ssr/interscroller/index.svelte
Adops have a requested that we have the JS tracking field added to the interscroller format, bringing it in to line with the fabrics.
Ad test was created, adops supplied a tag.
https://www.theguardian.com/games/article/2024/aug/21/atomfall-nuclear-catastrophe-lake-district-fallout?adtest=tracking_test
https://admanager.google.com/59666047#creatives/creative/detail/line_item_id=6772751927&creative_id=138486993391
I can see the tag attached and see it firing via the network tab.
> Interscroller: Adding JS  tracking field

- src/templates/csr/capi-multiple-paidfor/index.svelte
In opt-out, the CAPI Multiple Paid For template is inheriting a default width of 100% for divs, which is breaking the template styling. Explicitly setting a default of `width: auto` fixes these styling issues.
> Default to width: auto for CAPI Multiple Paid For template

- .husky/post-merge
When I pulled the latest changes in this repo I expected the changed dependencies to automatically be installed but instead I got this error. 
This PR fixes this issue by adding `corepack enable pnpm` to husky _post-merge_ hook.
> Fix error message for husky post-merge

- src/templates/ssr/fabric-custom/index.ts
- src/templates/ssr/fabric-custom/test.json
This PR removes the ThirdPartyTag from being sumoned from the fabric templates
Originally, this functionality allows us to pull third-party tags, but we currently don’t use or receive them.
If we ever need to use a third-party JS tag in the future, it can be added to a fabric custom template instead.
Run loacally to ensure the `Inputs` section of the preview doesnt have the `ThirdPartyTag input.
The fabrci template should function as normal populated by GooglePixel 2 ads.
| Before | After |
|--------|------|
|<img width="431" alt="Screenshot 2024-12-18 at 14 13 14" src="https://github.com/user-attachments/assets/0fbf6395-7d77-4f84-a80a-a4714817d49d" />| <img width="500" alt="Screenshot 2024-12-18 at 14 18 14" src="https://github.com/user-attachments/assets/0050ba36-3a89-440a-8f67-5d7e4d8cd …
> remove ThirdPartyTag from custom templates

- playwright/fabric-custom.test.ts
- playwright/fabric-video.test.ts
- playwright/fabric-xl.test.ts
Adds visual regression tests for the Fabric XL and Fabric video templates. For the Fabric video templates, we remove the autoplay property from the creative when testing, otherwise we would get false positives caused by differing amounts of progress through the video ads.
Also re-enables the Fabric Custom test for most viewport sizes. We turned off this test as it was being flaky. I've looked into it a little and for some reason, it's always the 980px viewport that fails the test, and the other sizes seem ok. I've re-enabled the tests for the other sizes because it's better to have some of the tests working than none at all.
> Update Fabric visual regression tests

- playwright/fabric-expandable.test.ts
Adds a visual regression test for the Fabric Expandable template. I've added a test for both the expanded and non-expanded views of the template, as that means this test will then cover the functionality of the template as well as the appearance.
> Add visual regression test for Fabric Expandable template

- package.json
- pnpm-lock.yaml
- src/lib/rollup.ts
The `@types/rollup-plugin-css-only` package lists 1 really old version of rollup as a dependency, which has a high severity vulnerability. The package hasn't been updated in years, so there's no update to resolve the out of date dependency, but we do still need it to handle the types of the css rollup plugin. Overriding the dependency to fix the vulnerability isn't ideal, but I think it's fine in this case, especially since it's a dev dependency.
> Override rollup dependencies to minimum version to fix vulnerability

- src/lib/fabric-custom-shared.ts
We're deprecating the old s3 URL by blocking public access, updating to the fastly one so fabric customs continue to work.
> Update fabric custom asset url

- src/lib/messenger.ts
- src/templates/components/Fabric.svelte
These messages will allow us to track the progress of fabric video and fabric video xl creatives.
The commercial bundle will listen for these messages and use them to setup progress reporting and update the progress, similar to video interscrollers at the moment.
> Add video init and progress messages to fabric video (xl)

- src/templates/components/Fabric.svelte
- src/templates/csr/fabric-video-xl/index.svelte
- src/templates/csr/fabric-video/index.svelte
The variables are slightly incorrect, this causes a deploy error and the templates to not update.
The error wasn't clear as the action didn't fail! Fixed in another PR #450 
```
[i] Updating native style "Web - Fabric Video".
[!] Error updating native style: [NativeStyleError.UNRECOGNIZED_PLACEHOLDER @ [0].htmlSnippet; trigger:'BackgroundImagePosition, BackgroundImageRepeat, BackgroundScrollType, MobileBackgroundImagePosition, MobileBackgroundImageRepeat']
...
[✔️] Native style "Web - Fabric - video -XL" with ID "705671" was found for template "fabric-video-xl".
[i] Updating native style "Web - Fabric - video -XL".
[!] Error updating native style: [NativeStyleError.UNRECOGNIZED_PLACEHOLDER @ [0].htmlSnippet; trigger:'BackgroundImagePosition, BackgroundImageRepeat, BackgroundScrollType, …
```
> Make sure template variables line up with GAM for fabric-video(-xl)

- docs/svelte-template-authoring.md
This PR updates the "Deploying your template" section in README with the correct information as deploying happens automatically now to GAM once a PR is merged to main after the changes from this https://github.com/guardian/commercial-templates/pull/337.
> Update "Deploying your template" section in README

- package.json
- pnpm-lock.yaml
Bumps the version of `@sveltejs/kit` to at least `2.37.0`
> Bump version of `@sveltejs/kit`
