guardian/commercial-templates

lib/html.js, package.json
The syntax is quite simple:
`{{#svg}}name-of-svg{{/svg}}`
There should be an `name-of-svg.svg` file in the `src/_shared/svgs` folder.
=> Include SVG via Hogan.js partials

src/_shared/js/messages.js
Creatives now can first wait to receive a message from the parent window that will communicate the ID of the iframe they reside in, and then send along that information on each message.
=> Get and send iframe ID

src/glabs-native-traffic-driver/index.html
Not editionalised, but this may need to be revisited in the future.
=> Add links to Glabs pages

README.md
=> Just a few changes

README.md
I appreciate we'll soon have a simpler preview process, but for now with multiple people working on this migration I thought it would make sense to centralise instructions for testing with DFP.
@regiskuckaertz please feel free to edit, streamline and add additional info.
=> README to explain workflow for preview & testing

build.js, clean.js, package.json, preview/build.js
Lots of steps in the preview process now, time to automate?
=> Added npm preview script.

package.json
Forgot to update this after changing the script dependencies =S.
=> Fix preview script

src/_shared/js/impl/promises.js, src/_shared/js/messages.js, src/books/index.js, src/travel/index.js
- The `resizeIframeHeight` did not wait for everything to be loaded before measuring the viewport height and so might send wrong information
- The `portify` function takes care of changing the port number when testing components using `nodemon`
- Introducing the `soon` utility function which offers an alternative way to read the DOM _after_ all DOM operations have been done. This is in contrast with the `requestAnimationFrame` method where we need to batch all the reads _before_ the writes.
=> A few improvements to Books and Travel

lib/html.js, src/_shared/js/config.js, src/_shared/scss/_advert.scss, src/_shared/scss/_adverts-soulmates.scss, src/soulmates/index.html, src/soulmates/index.js, src/soulmates/index.scss, src/soulmates/test.json
[Here it is.](https://www.youtube.com/watch?v=z5dpYDTEMRU)
**Old**
**Native**
This is the first template I've done so I'm fully prepared for a wave of comments and changes.
We could add in a parameter for the number of soulmates cards to render (we take 6 by default, but since we render each card as it comes, we could vary this and provide control of this in DFP. This functionality isn't currently present but it would be trivial to implement.
=> Soulmates Native

src/soulmates/index.html
I'm an idiot and didn't actually pass in the soulmates URL.
We could supply it as a variable but probably not worth it.
=> Provide the actual soulmates URL rather than a placeholder.

src/soulmates/index.js
I was accidentally (and hilarious) linking each `advert` to the picture contained therein. Thought it best to link to the actual profile, as desired.
=> Reflect changes in Member definition on frontend.

build.js, lib/build.js, lib/js.js, package.json
(the ability to explicitly provide a minification directive to `build.js`)
=> ASK AND YOU SHALL RECEIVE

src/_shared/js/messages.js
Small mistake in `getIframeId`.
=> Defensive checking in getIframeId

src/manual-multiple-membership/index.js, src/manual-multiple-soulmates/index.js, src/manual-multiple/index.js, src/manual-single/index.js
Otherwise it is receiving whatever `getIframeId` returns.
=> Call getWebfonts explicitely without args

src/_shared/scss/_adverts.scss, src/manual-inline/index.html, src/manual-inline/index.js, src/manual-inline/index.scss, src/manual-inline/test.json
This reverts part of commit 770c6eff7d6cb84d850bab6c54159be93406635d.
Work from PR #52 was accidentally removed in PR #54, this reinstates
that work.
PR #54 removed the manual-inline files that were merged into master in PR #52, this will just reinstate them back into master.
@annebyrne
=> Revert "Changes following Regis' comments"

src/_shared/js/messages.js, src/fabric/index.js
Also fixes a bug where the callback listener was undefined. Related to [this PR](https://github.com/guardian/frontend/pull/14613).
@Ap0c @JonNorman @Calum-Campbell @annebyrne so you can update your creatives should you need it, when the viewport gets resized.
=> Handle Fabric fixed and parallax effects

lib/js.js, src/_shared/js/dom.js, src/_shared/js/messages.js, src/manual-multiple/index.html, src/manual-multiple/index.js
This, with [the listener on the other end](https://github.com/guardian/frontend/pull/14620), will send events to GA whenever a user clicks a link inside the ad.
=> Report clicks to the parent frame

src/manual-gimbap-richmedia/index.html, src/manual-gimbap-richmedia/index.scss, src/manual-gimbap-richmedia/test.json
- Quick update on work done in https://github.com/guardian/commercial-templates/pull/76
- Just adding blink to html
=> update gimbap richmeadia

src/fabric-video/index.html, src/fabric-video/index.js, src/fabric-video/index.scss
=> Add Fabric Video template

src/fabric-video/index.html, src/fabric-video/index.js, src/fabric/index.js
In Fabric, because of a return statement in the background handling code, the layer2 handling code might never get called. So I fixed that.
Also small improvement in Fabric Video where the layer2 has been given an ID.
=> Fix out of scope code issue

src/inline-liveevents/index.js
Does what it says on the tin and HOPEFULLY SETS OFF A TEAM CITY BUILD?!?!?!!!!!1111####
=> Corrects the case of EventID DFP variable to match that in DFP.

build.js, lib/js.js, src/_shared/js/capi-multiple.js, src/_shared/js/dom.js, src/_shared/js/utils.js, src/blended/index.js, src/books/index.js, src/capi-single-paid/index.js, src/capi-single-supported/index.js, src/glabs-native-traffic-driver/index.js, src/inline-liveevents/index.js, src/jobs/index.js, src/soulmates/index.js, src/travel/index.js
In this PR, we
- start using the FT polyfills service (our own hosted version)
- sign the root element with feature-detected classes
- manually polyfill `URLSearchParams`
cc @janua
=> JavaScript and CSS progressive enhancement

src/_shared/js/ui.js, src/capi-single-paid/index.js, src/fabric-video-expandable/index.html, src/fabric-video-expandable/index.js, src/fabric-video-expandable/index.scss
Behold! The Fabric Video Expandable.
cc @JonNorman @janua @Calum-Campbell
=> Fabric Video Expandable

src/_shared/scss/_core.scss, src/fabric-expandable/index.html, src/fabric-expandable/index.js, src/fabric-video-expandable/index.html, src/fabric-video-expandable/index.js, src/fabric-video/index.html, src/fabric-video/index.js, src/fabric-video/index.scss, src/fabric/index.html, src/fabric/index.js
=> Add optional "Advertisement" label to Fabrics

src/_shared/js/ads.js, src/_shared/js/capi-multiple.js, src/_shared/scss/_advert.scss, src/_shared/scss/_adverts-capi.scss, src/_shared/scss/_adverts.scss, src/capi-multiple-paidfor/web/index.html, src/capi-multiple-paidfor/web/index.scss, src/capi-single-paid/test.json, src/capi-single-paid/web/index.html, src/capi-single-paid/web/index.js, src/capi-single-supported/test.json, src/capi-single-supported/web/index.html, src/capi-single-supported/web/index.js
See https://docs.google.com/document/d/1DfX_8GA-_C5jzH2AdeGHQTpoO-K9lY47DmNZ4i9HZ2E/edit?ts=58106c9d
=> Fix QA reported bugs

src/glabs-native-traffic-driver/app/index.scss
Small PR, I'll give myself a +1
=> Remove max-width constraint on app traffic driver

src/_shared/js/capi-multiple.js, src/_shared/scss/_adverts-capi.scss, src/_shared/scss/_adverts.scss, src/_shared/scss/_brandbadge.scss, src/_shared/scss/_helpers.scss, src/_shared/scss/_paidfor-meta.scss, src/_shared/scss/_popup-paidfor.scss, src/capi-multiple-paidfor/web/index.html, src/capi-multiple-paidfor/web/index.js, src/capi-multiple-paidfor/web/index.scss, src/capi-multiple-supported/test.json, src/capi-multiple-supported/web/index.html, src/capi-multiple-supported/web/index.js, src/capi-single-paid/web/index.scss
Pretty self-explanatory
@ScottPainterGNM @JonNorman
=> CAPI multiple supported: QA fixes

src/_shared/scss/_core.scss, src/fabric/app/index.html, src/fabric/web/index.js
Just renamed variables and values. Also, on app-specific, the label isn't necessary.
=> Fabric fixes from Tijana

src/guardian-hosted/web/index.scss
=> Hosted by container - design review changes

src/_shared/scss/_core.scss, src/fabric-expandable/web/index.html, src/fabric-expandable/web/index.js, src/fabric-expandable/web/index.scss, src/fabric-video-expandable/web/index.html, src/fabric-video-expandable/web/index.js, src/fabric-video-expandable/web/index.scss, src/fabric-video/web/index.html, src/fabric/web/index.html
This PR fixes a few bugs discovered by Tijana while testing. It also adds the tracking pixel which was missing from all the Fabrics.
=> Fabric video expandable: Tijana's feedback fixes

src/blended/web/index.js, src/books/web/index.html, src/jobs/web/index.html
Nothing else to say here, move along.
=> Use HTTPS for client-facing links and use the bookshop link on books, not Holidays

src/_shared/scss/_defaults.scss, src/fabric-expandable/web/index.scss, src/fabric-video-expandable/web/index.scss
Addresses two issues reported by Scott and Tijana during QA:
- buttons in FF are distorted because of a proprietary style issue
- shadows were not 100% correct
=> Fabric (Video) Expandable fixes

src/google/web/index.scss
=> Add google creative

src/manual-single/web/index.scss
A loooooot of missing styles in the manual single.
=> Add missing styles

lib/js.js, src/_shared/js/impl/promises.js, src/fabric-video/web/index.js, src/fabric-video/web/index.scss
Check support for `object-fit` and provide alternate layout if not.
=> Fabric Video fix on IE

src/manual-multiple-soulmates/test.json, src/manual-multiple-soulmates/web/index.html
Before:
After:
To do: update in DFP (requires changes to format variables)
=> Manual multiple soulmates - replace fourth card with form

src/_shared/js/creatives.js, src/_shared/scss/_adverts.scss, src/manual-multiple-membership/web/index.js, src/manual-multiple-soulmates/test.json, src/manual-multiple-soulmates/web/index.html, src/manual-multiple-soulmates/web/index.js, src/manual-multiple-soulmates/web/index.scss, src/manual-multiple/web/index.js
Allows user to choose between showing the fourth card and the form:
=> Manual multiple soulmates

src/_shared/js/capi-multiple.js, src/capi-single-paid/web/index.js
should look for logo link in correct place (following change in API response structure)
=> cAPI paid for logos

preview/src/js/lib/fetch.js
@katebee this is as far as I got trying to make the preview tool work in IE - it at least made the dropdown work as far as I can remember!
=> Add missing import

src/_shared/scss/_hosted-native-card.scss, src/hosted-native-traffic-driver/amp/index.scss, src/hosted-native-traffic-driver/test.json, src/hosted-native-traffic-driver/web/index.js
- remove height restriction so longer headlines aren't truncated
- add missing click macro
=> Hosted native card (web) - fix

.gitignore, README.md
The readme has been updated for clarity.
=> Introduce .gitignore and readme update

src/google/web/index.scss
See live version: https://www.theguardian.com/uk/culture?adtest=google_native&ad-unit=google_native
=> Google native mk2 design updates

src/carrot/test.json, src/carrot/web/index.html, src/carrot/web/index.js, src/carrot/web/index.scss
This is a rough PoC for creating a small traffic driver ad slot.
To do:
**Mobile**:
**Tablet**:
**Desktop**:
=> A PoC for driving traffic to GLabs content.

README.md, build.js, src/_shared/js/utils.js, src/revealer/web/index.html, src/revealer/web/index.js, src/revealer/web/index.scss
New Native format for the old revealer template.
=> Fabric mobile revealer

src/glabs-inline/web/index.js, src/glabs-inline/web/index.scss, src/glabs-left/test.json, src/glabs-left/web/index.html, src/glabs-left/web/index.js, src/glabs-left/web/index.scss
**From design mockup**
*Mobile*
*Tablet/Desktop*
**From preview**
*Mobile*
*Desktop*
=> Create Glabs Left native style

.sass-lint.yml, README.md, package.json, src/glabs-native-traffic-driver/amp/index.scss, src/glabs-native-traffic-driver/app/index.scss, src/glabs-native-traffic-driver/web/index.scss
- Add sass-lint to the project
- Add pre-commit so we can run scripts before a commit completes
- Add lint-staged so we can restrict targeting of scripts to staged files
- Use pre-commit, lint-staged and sass-lint to validate sass and enforce conventions
The purpose of this PR is to establish (and enforce 😈 ) some sass conventions as new code is added to the codebase.
The sass-lint config (sass-lint.yml) is based on the [current one from Guardian frontend](https://github.com/guardian/frontend/blob/ca566a2ccefddc7c80056bc2c46eeaf99f234935/.sass-lint.yml) and I'm keen to defer to frontend if the conventions change. Sharing standards keeps things simple, and frontend has the lovely dedicated platform team to focus on this stuff.
the awesome combo of `lint-staged` and `pre-commit` will now …
=> Add sass-lint and enforce a pre-commit check 💅 😎

src/fabric/app/index.scss, src/fabric/web/index.scss
Final fixes for issue #152  and linked to PR #158
=> Resolved sass issue, removed duplicate animation properties in block

build.js, lib/css.js, src/_shared/js/messages.js, src/mobile-revealer/test.json, src/mpu-parallax/test.json, src/mpu-parallax/web/index.html, src/mpu-parallax/web/index.js, src/mpu-parallax/web/index.scss
This is a broad copy of the mobile-revealer template with a few changes.
Given the time pressure on getting this done, I will leave it to a later date to merge the two into a single template.
=> New Format: MPU Parallax

src/fabric-custom/test.json, src/fabric-custom/web/index.html
Adds pixels and a viewability tracker for our Fabric custom template.
=> Add tracker and pixels to Fabric custom

src/_shared/scss/_gimbap-wrap.scss, src/capi-multiple-nologos/test.json, src/capi-multiple-nologos/web/index.html, src/capi-multiple-nologos/web/index.js, src/capi-multiple-nologos/web/index.scss, src/gimbap-simple/web/index.html
- add <a> tag and text-decoration:none to wrap message in DFP gimbap-simple template
=> Add <a> tag to gimbap wrap message

src/capi-multiple-paidfor/web/index.js, src/capi-multiple-paidfor/web/index.scss, src/capi-multiple-supported/test.json, src/manual-multiple/test.json
Changed the display:inline-block to position logo to the right rather than the left.
=> Update paid logo position to right-hand side of container

src/carrot/test.json, src/carrot/web/index.html, src/carrot/web/index.scss
Updating carrot styling to match editorial rich links (font size in rems rather than px).
=> Carrot code updates

src/carrot/web/index.scss
=> Change carrot brand logo size and standfirst line height

src/_shared/scss/_palette.scss
Change the header from blue to grey
=> Change header color of Weekly templates

src/fabric/web/index.html, src/fabric/web/index.js, src/fabric/web/index.scss
Tweeked padding for Fabrics with scrollType of parallax selected only, so top layers align left and right.
=> Sw fabric parallax padding

src/_shared/scss/_adverts-lifestyle.scss, src/_shared/scss/_palette.scss, src/manual-multiple/web/index.html, src/manual-multiple/web/index.scss, src/manual-single/web/index.html, src/manual-single/web/index.scss
Adding lifestyle colour to Manual Single and Manual Multiple Native Templates 
**Manual Multiple** 
**Manual Single**
=> Adding lifestyle colour to Manual Single and Manual Multiple Native Templates 

src/carrot-third-party/test.json, src/carrot-third-party/web/index.html, src/carrot-third-party/web/index.js, src/carrot-third-party/web/index.scss
Creates a new exactly the same carrot native format with an additional Tracking Pixel:
` <img src="[%TrackingPixel%]%%CACHEBUSTER%%" class="creative__pixel">`
Fluid • Creative template
Style name: Carrot - 3rd party tracking
=> New Carrot native format with third party pixel

src/interscroller/web/index.html, src/interscroller/web/index.js
- Add third party pixels to Interscroller Ad
- Switch using GAM macro for destination URL
=> Add third party pixels to Interscroller Ad

.gitignore
VS Code creates a directory containing settings etc. We don't want this
putting in the repo in the same way we currently ignore IntelliJ's
settings folder.
=> Update .gitignore to incloude vscode folder

package-lock.json
We should be version controlling the `package-lock.json` file.
=> Add `package-lock.json` to repo

src/_shared/scss/_adverts-climate.scss, src/manual-multiple/web/index.html
As per the request from AUS team adding a new template tone for changing the background colour & text colour of the first Panel of the Web Multiple template
=> Adding a new template for AUS

src/_shared/js/events-multiple.js, src/events-multiple/web/index.html
URLs were being built incorrectly and weren't being added to the correct
element.
This fixes that and ensures that tracking info is appended.
=> Add tracking to URL and fix clickthrough

src/_shared/scss/_adverts-support.scss, src/_shared/scss/_palette.scss, src/manual-multiple/web/index.html, src/manual-multiple/web/index.scss, src/manual-single/web/index.html, src/manual-single/web/index.scss
Adds a new tone for Merch Multiple & Merch Single templates. AUS team needs it for our upcoming 'supporter moment'.
=> Add support colour for AUS

src/_shared/scss/_adverts-subs-rebrand.scss, src/_shared/scss/_palette.scss, src/manual-multiple/test.json, src/manual-multiple/web/index.html, src/manual-multiple/web/index.scss
=> Add subs-rebrand tone to manual multiple

src/manual-single/web/index.html
Reopen https://github.com/guardian/commercial-templates/pull/252
It got closed automatically when I deleted master branch and renamed to main 🙈
I've know merged main into it and re-opened
=> (@MarSavar) remove SVG duplication 

.editorconfig
Update .editorconfig to reflect latest changes to https://github.com/guardian/configs/blob/main/.editorconfig
=> Update editorconfig in line with guardian/configs

.eslintrc.cjs, .github/workflows/CI.yml, .github/workflows/PR.yml, DESIRES.md, README.md, docs/legacy-to-svelte-migration.md, docs/svelte-template-authoring.md, src/app.html, src/lib/gam.ts, src/lib/rollup.ts, src/routes/__layout.svelte, src/routes/csr/[template].json.ts, src/routes/index.svelte, src/routes/ssr/[template].json.ts, src/routes/ssr/[template].svelte, src/templates/components/PaidForHeader.svelte, src/templates/components/Sponsor.svelte, src/templates/components/icons/GuardianLabs.svelte, tsconfig.json
- Ran prettier on the repository and made some formatting changes to comply with those standards
- Added some github actions to run when a pull request is created to lint the code and check the types
I think we'll need to open some pull requests to check if the tests run as expected?
Edit: It has linted itself 
We'll be keeping more consistent code style by spotting linting errors before merging pull requests instead of having to do bulk fixes every now and then
=> Add linting and typescript checks for pull requests

src/lib/Previews.svelte, src/lib/cmp.ts, src/lib/messenger.ts, src/lib/messenger/get-page-url.ts, src/lib/public-good.ts, src/lib/rollup.ts, src/routes/csr/[template].json.ts, src/templates/csr/public-good/index.svelte
Add template for Public Good Native template
This is in the new svelte templating
=> Add template for Public Good

README.md
This PR replaces the broken link to Svelte templates doc in Readme.
Test locally and check the link works.
=> Replace broken link to Svelte template doc in Readme

src/templates/csr/fabric-xl/index.svelte, src/templates/csr/fabric/index.svelte, src/templates/ssr/interscroller/index.svelte, src/templates/ssr/manual-inline/index.svelte, src/templates/ssr/manual-single/index.svelte
Remove unused references to polyfill.io
=> Remove unused references to polyfill.io

README.md, docs/svelte-template-authoring.md
This PR updates the docs by replacing `yarn` with `pnpm` as now this repo uses `pnpm`.
Up-to-date docs to avoid confusion.
=> Update docs after migration to pnpm

playwright/capi-single-paidfor.test.ts
Adds a visual regression test for the CAPI Single PaidFor template.
=> Add CAPI Single PaidFor test
